### ISSUE TITLE
It failed in iOS

### ISSUE THREAD

**Issue by CongBaDo** [NGhebreial/flutter_exif_rotation#12]
`Unhandled Exception: MissingPluginException(No implementation found for method rotateImage on channel flutter_exif_rotation)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      FlutterExifRotation.rotateImage (package:flutter_exif_rotation/flutter_exif_rotation.dart:15:38)
<asynchronous suspension>`

I tested on ip8+

**Comment by NGhebreial** [comment]
I don't have the implementation for iOS... As you can see in the readme, right now I don't have a macOS so I can't implement it, sorry :(
