### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method rotateImage on channel flutter_exif_rotation)

### ISSUE THREAD

**Issue by Bhagatcliffex** [NGhebreial/flutter_exif_rotation#13]
When I pick image from gallery or camera I got this exception - Unhandled Exception: MissingPluginException(No implementation found for method rotateImage on channel flutter_exif_rotation)

**Comment by VictorCamargo** [comment]
> When I pick image from gallery or camera I got this exception - Unhandled Exception: MissingPluginException(No implementation found for method rotateImage on channel flutter_exif_rotation)

Did you fixed it?
