### ISSUE TITLE
rotateImage method is not find in ios.

### ISSUE THREAD

**Issue by fullstack-cliffex** [NGhebreial/flutter_exif_rotation#15]
This plugin is working for android not for ios .How to do this for ios?

**Comment by NGhebreial** [comment]
Basically I need a macOS and I don't have access to one, so for now I will not implement it

**Comment by fullstack-cliffex** [comment]
Ok thanks.I have implemented it in ios.

**Comment by NGhebreial** [comment]
If you want, you can make a pull request and I will publish it
