### ISSUE TITLE
iOS compile issue.

### ISSUE THREAD

**Issue by success-0627** [NGhebreial/flutter_exif_rotation#17]
![image](https://user-images.githubusercontent.com/53897531/66205557-e07a9d80-e6d7-11e9-821d-5c47d749dcb1.png)

![image](https://user-images.githubusercontent.com/53897531/66205614-09029780-e6d8-11e9-90f1-d6f29a5c3e09.png)

**Comment by success-0627** [comment]
@NGhebreial 
Thank you for your fast turn around.
Would you please version up and publish?

**Comment by NGhebreial** [comment]
Yes I'm working on it because the merge was made incorrectly, as soon as I get it I will publish it :)
Thanks a lot!
