### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by lifenautjoe** [NGhebreial/flutter_exif_rotation#2]
Does this still works? Getting a `Raw image not detected`

**Comment by NGhebreial** [comment]
This message is being thrown by the plugin `image_picker` not by this one.
Is it working despite of that message?

**Comment by lifenautjoe** [comment]
Nope, the rotation bug is back 😱. 

Alpha access right now and golden supporter badge on https://openbook.social if you can help out 😢.

**Comment by NGhebreial** [comment]
Ok let me take a look and let's try to fix it again.
Can you tell me which device and version of android are you using?

**Comment by lifenautjoe** [comment]
![image](https://user-images.githubusercontent.com/12737509/54697064-3b2e1c80-4b2d-11e9-9c8d-14099510ee59.png)

Thank you!

**Comment by NGhebreial** [comment]
I was taking a look to the emulator and it seems that is a bug, I am not sure if this is happening also in real devices... When I made that plugin I was testing mainly on real devices and it was working fine.
Have you tried to test it in a real device?

**Comment by lifenautjoe** [comment]
Hah.. I haven't 🤔.

Anyhow, we added an image cropper/rotator for now until the bug is fixed on the flutter plugin.


Drop me an email at joel@open-book.org and I'll be super happy to send you an invite to join Openbook! The mobile app is a pushing to the boundaries, full-blown flutter app.

Have a great day!

**Comment by lifenautjoe** [comment]
On a device with SDK 28 I'm getting 

````
E/MediaStore(22074): Failed to insert image
E/MediaStore(22074): java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=22074, uid=10088 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
E/MediaStore(22074): 	at android.os.Parcel.createException(Parcel.java:1942)
E/MediaStore(22074): 	at android.os.Parcel.readException(Parcel.java:1910)
E/MediaStore(22074): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
E/MediaStore(22074): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/MediaStore(22074): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
E/MediaStore(22074): 	at android.content.ContentResolver.insert(ContentResolver.java:1587)
E/MediaStore(22074): 	at android.provider.MediaStore$Images$Media.insertImage(MediaStore.java:982)
E/MediaStore(22074): 	at android.provider.MediaStore$Images$Media.insertImage(MediaStore.java:908)
E/MediaStore(22074): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.rotateImage(FlutterExifRotationPlugin.java:104)
E/MediaStore(22074): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.onMethodCall(FlutterExifRotationPlugin.java:49)
E/MediaStore(22074): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MediaStore(22074): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MediaStore(22074): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MediaStore(22074): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MediaStore(22074): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MediaStore(22074): 	at android.os.Looper.loop(Looper.java:160)
E/MediaStore(22074): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MediaStore(22074): 	at java.lang.reflect.Method.invoke(Native Method)
E/MediaStore(22074): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MediaStore(22074): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
````

**Comment by lifenautjoe** [comment]
Nvm.. it's about file permissions. Sorry for the spam!

**Comment by NGhebreial** [comment]
Are you still having troubles with the image orientation?

**Comment by lifenautjoe** [comment]
I couldn’t get the permissions package to work. And for some reason it
requires external storage permission.. Is it writing the fixed file there?
Does temp storage not requires this ?

**Comment by NGhebreial** [comment]
I was taking a look and I missed the part of asking for permissions, I am going to implement that in a fast way just to fix it, later I will make another release to fix it properly

**Comment by lifenautjoe** [comment]
Awesome @NGhebreial ! Thank you

**Comment by lifenautjoe** [comment]
Hi @NGhebreial ! Have you perhaps had some time to look into this?

People over at Openbook would greatly appreciate.. tons of rotated photos haha.

**Comment by NGhebreial** [comment]
Hi @lifenautjoe 
I didn't, now I am in a busy moment and it's being difficult to find some time.
Also, I would like to test this with a real device, because the data I receive from the emulator is not correct.
Anyway, I want to take a look as soon as I can :)

**Comment by NGhebreial** [comment]
I just tried with a sony device, which gives wrong data and the plugin is working without problems.

Take into account that this plugin just checks the orientation attribute of the picture, usually samsung and sony devices gives you the orientation like if the pictures was taken in landscape when is not.
The problem with the emulator is that it gives you a fake image with a fake orientation, this plugin is not working with it.

Did you try with a physical device?

**Comment by NGhebreial** [comment]
@lifenautjoe  Any news?

**Comment by vy12021** [comment]
Support ios?

**Comment by lifenautjoe** [comment]
No it does not have an iOS implementation @vy12021 .

@NGhebreial , yes, tested on physical devices and users of the app can also confirm the bug on Samsung devices 😬

**Comment by lifenautjoe** [comment]
I think the problem here is no longer whether the plugin works but because the permissions are missing, it crashes 😞

**Comment by NGhebreial** [comment]
Yes that's true... The example I provide works because I am using a plugin that already asks for permissions before. I will work on the permissions part as soon as I can to fix it, sorry for the delay

**Comment by NGhebreial** [comment]
@lifenautjoe Sorry for the long delay, my job is not with Flutter anymore and is getting hard find time to fix my plugins.
I think this time I fixed it, can you take a look?
