### ISSUE TITLE
Use spec.swift_version instead of Podfile instructions in README

### ISSUE THREAD

**Issue by ksheremet** [NGhebreial/flutter_exif_rotation#26]
Setting [`swift_version`](https://guides.cocoapods.org/syntax/podspec.html):

```
spec.swift_version = '4.2'
```

in the `.podspec` file of this plugin should be sufficient to require version 4.2:

```
UIKit.UIImage:60:17: note: 'jpegData(compressionQuality:)' was introduced in Swift 4.2
```

This is a less intrusive way than updating the generated file `Podspec` in user projects.

**Comment by febg11** [comment]
Hi ksheremet, is this the flutter.podspec?If not where is this file located? Thanks

edit

I cannot get this to work with IOS at all

**Comment by yukitaka13-1110** [comment]
Any updates ?

**Comment by NGhebreial** [comment]
I just published the changes on the podspec so this should be done 👍
