### ISSUE TITLE
'flutter_exif_rotation/flutter_exif_rotation-Swift.h' file not found

### ISSUE THREAD

**Issue by thong21012** [NGhebreial/flutter_exif_rotation#28]
![Screen Shot 2020-05-05 at 1 57 05 PM](https://user-images.githubusercontent.com/21187300/81041556-5813e380-8ed8-11ea-9475-433a6d1ef2f4.png)

Can you help me, sir !

**Comment by NGhebreial** [comment]
Is this still happening?

**Comment by yozhik2007** [comment]
Had the same issue.

1. Right-click on Runner in the Project Navigator on the left, and click New File
2. Create a single empty Swift file
3. Press Create Bridging Header
4. Replace #import <flutter_exif_rotation/flutter_exif_rotation-Swift.h> with #import <flutter_exif_rotation-Swift.h>

Hope it helps.
