### ISSUE TITLE
Getting MissingPluginException

### ISSUE THREAD

**Issue by sunojvijayan** [NGhebreial/flutter_exif_rotation#3]
When I use this pluggin for iOS i get this error.

flutter: MissingPluginException(No implementation found for method rotateImage on channel flutter_exif_rotation)

**Comment by NGhebreial** [comment]
Yes, the plugin is not implemented for iOS because I don't have a mac and I can't implement it. So far I will not do it but feel free to make a pull request with the implementation :)

**Comment by sunojvijayan** [comment]
Thanks.
