### ISSUE TITLE
Saves rotated image in different location.

### ISSUE THREAD

**Issue by zbejas** [NGhebreial/flutter_exif_rotation#33]
After rotating and saving a certain image i get this:

```
flutter: /var/mobile/Containers/Data/Application/179EE26B-B564-4D40-8CE8-6572B202B9C9/Library/Caches/1602506969364.jpg
flutter: Size( 1280, 720 )
flutter: Flipping!
/var/mobile/Containers/Data/Application/179EE26B-B564-4D40-8CE8-6572B202B9C9/Documents/apple.jpg
flutter: rotateAndSaveImage return path: /var/mobile/Containers/Data/Application/179EE26B-B564-4D40-8CE8-6572B202B9C9/Documents/apple.jpg

```

As you can see my image is moved and renamed. Line 1 is directory of saved file. Last line is the directory of rotated image.
Also string `apple.jpg` is set by itself. I have not put in any lines tha would rename a file after rotation. 
This only happens in IOS, on Android it works as advertised.

Code:
```
if (imageSize.width > imageSize.height) {
      //io.File(directory).exists().then((value) => print('File: $value'));
      print('Flipping!');
      io.File image =
          await FlutterExifRotation.rotateAndSaveImage(path: directory);
      //image.copy(directory);
      print('Flipped!');
      if (image != null) return true;
    }
```

**Comment by NGhebreial** [comment]
I believe someone made a PR to fix this, can you check if it's still happening?

**Comment by zbejas** [comment]
> 
> 
> I believe someone made a PR to fix this, can you check if it's still happening?

Nope, still happening.
