### ISSUE TITLE
iOS deployment target

### ISSUE THREAD

**Issue by kliyer-ai** [NGhebreial/flutter_exif_rotation#36]
Why was the iOS deployment target set to 14.0 in the podspec file? Is the iOS code not compatible with lower versions?
Thanks!

**Comment by mastahnish** [comment]
I have the same observation. Can we analyze this case asap?

**Comment by buzzySmile** [comment]
The same issue.
Resolve this by downgrading to previous plugin version

```
dependencies:
  ...
  flutter_exif_rotation: 0.3.0
```

**Comment by kliyer-ai** [comment]
@buzzySmile You are right and I am aware of that but I think it's still a bit unfortunate as it prevents me/us from using any future updates ...

**Comment by NGhebreial** [comment]
Let me fix this, I'll put a new version as latest tomorrow! sorry for the delay

**Comment by NGhebreial** [comment]
I published a new version and it should be solver, sorry for the inconvenience
