### ISSUE TITLE
iOS Freezes when waiting on invokeMethod

### ISSUE THREAD

**Issue by dvaldivia** [NGhebreial/flutter_exif_rotation#38]
Hi, I think something might have broken in iOS due to the null-safety PR I sent (sorrry) 

I've been debugging it for hours, but can't figure out why when the `invokeMethod` future is awaited, it just sits there and I see no prints on the swift side.

I'm using flutter 2 so I'm not sure if that has anything to do, I do see, the minimum flutter requirement is 1.13 not, sure if that has anything to do

Another theory on why this only happen on iOS is that perhaps the `pod.spec` is still referencing `0.3.0` tag perhaps?

Here's a quick patch of both places with the old references

```
diff --git a/ios/flutter_exif_rotation.podspec b/ios/flutter_exif_rotation.podspec
index 23b23c0..db72706 100644
--- a/ios/flutter_exif_rotation.podspec
+++ b/ios/flutter_exif_rotation.podspec
@@ -3,7 +3,7 @@
 #
 Pod::Spec.new do |s|
   s.name             = 'flutter_exif_rotation'
-  s.version          = '0.3.0'
+  s.version          = '0.4.0'
   s.summary          = 'Flutter plugin that fixes the picture orientation'
   s.description      = <<-DESC
     Flutter plugin that fixes the picture orientation when taken in landscape for some devices.
@@ -11,7 +11,7 @@ Pod::Spec.new do |s|
   s.homepage         = 'https://github.com/NGhebreial/flutter_exif_rotation'
   s.license          = { :type => 'BSD' }
   s.author           = { 'Nadia Ghebreial' => 'nadiagnieto@gmail.com' }
-  s.source           = { :git => 'https://github.com/NGhebreial/flutter_exif_rotation.git', :tag => 'v0.3.0' }
+  s.source           = { :git => 'https://github.com/NGhebreial/flutter_exif_rotation.git', :tag => 'v0.4.0' }
   s.source_files = 'Classes/**/*'
   s.public_header_files = 'Classes/**/*.h'
   s.dependency 'Flutter'

```

**Comment by devjeff** [comment]
I have the same issue and I think, I've found the problem. When you look at this code (SwiftFlutterExifRotationPlugin.swift):
```
if let updatedImage = image?.updateImageOrientationUpSide() {
                
                let fileManager = FileManager.default
                let file_name = NSURL(fileURLWithPath: imagePath).lastPathComponent!
                let paths = (NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0] as NSString).appendingPathComponent(file_name)
                let imageData = updatedImage.jpegData(compressionQuality: 0.8); fileManager.createFile(atPath: paths as String, contents: imageData, attributes: nil)
                
            } else {
                result(imagePath)
            }
```

you can see that there is no call to the "result" method in the if block. Thus, a result for the method call is never returned to Flutter.

**Comment by devjeff** [comment]
How quickly can this be fixed? It would be really cool to have this feature in our upcoming release.

**Comment by dvaldivia** [comment]
@devjeff what I observed while debugging is that the swift code is not being called now, I added a few print statements, but I'm not sure if they are supposed to show
