### ISSUE TITLE
app crash if used with pickImage(source: ImageSource.camera)

### ISSUE THREAD

**Issue by juliengit2** [NGhebreial/flutter_exif_rotation#4]
The plugin doesn't work if used with ImageSource.camera (okay if ImageSource.gallery)

File image = await ImagePicker.pickImage(source: ImageSource.camera);
image = await FlutterExifRotation.rotateImage(path: image.path);

pity

>  Alloc sticky concurrent mark sweep GC freed 25(9KB) AllocSpace objects, 0(0B) LOS objects, 6% free, 113MB/121MB, paused 640us total 7.537ms
> I/art     (28472): Clamp target GC heap from 129MB to 128MB
> I/art     (28472): Alloc partial concurrent mark sw

> Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).
> '
>     r0 00000000  r1 00006f38  r2 00000006  r3 00000000
>     r4 b6f28114  r5 00000006  r6 00000058  r7 0000010c
>     r8 be857e14  r9 be857e60  sl 00000066  fp aec79290
>     ip 00006f38  sp be857cf0  lr b6eb1fc5  pc b6ed5a4c  cpsr 600

**Comment by NGhebreial** [comment]
I think this crash is not from the plugin, I tested it and for me it's working.
Can you give me more details?
Thanks

**Comment by juliengit2** [comment]
Hi, thank you for your email, it's strange because if I remove the call of your plugin after ImageSource.camera:
image = await FlutterExifRotation.rotateImage(path: image.path);

then it's working fine... FlutterExifRotation seems to work only with source = ImageSource.gallery

Is it working for you with ImageSource.camera ?

**Comment by NGhebreial** [comment]
Yes, and usually I use it with `ImageSource.camera` 
I know it's a silly question but, did you check the variable `image` is not null?

**Comment by juliengit2** [comment]
yes of course, and I get the picture from ImageSource.camera if I remove FlutterExifRotation (it crash when I add FlutterExifRotation)

on which device have you tested? and a physical device or an emulator? 'cause it seems to be a memory issue

**Comment by NGhebreial** [comment]
I tested in two different physical devices and with the emulator and everything is ok.
Have you tested in a physical device? which version of android are you using?

**Comment by juliengit2** [comment]
strange, I'm also working with a physical device, android 5.0.1 (galaxy s4)

**Comment by NGhebreial** [comment]
I just checked with an emulator with that android version and ok for me... 
As you said before, it seems a memory issue from the VM, but I am not sure if it's because the plugin or from something else

**Comment by NGhebreial** [comment]
@juliengit2 any news?
