### ISSUE TITLE
Doesn't work when tested for first time

### ISSUE THREAD

**Issue by Enlacecode** [NGhebreial/flutter_exif_rotation#41]
When Installed app freshly and tested for the first time nothing happens, i.e. it doesn't give rotated image in the response, it works when tested for the 2nd time, 3rd time and so on.

Tested on both Physical device and Emulator - Android 10.

@NGhebreial Please refer to this.

**Comment by fernandovaquero** [comment]
The problem is here 
`    public void rotateImage() {

        if (!permissionManager.isPermissionGranted(Manifest.permission.READ_EXTERNAL_STORAGE) || !permissionManager.isPermissionGranted(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
            permissionManager.askForPermission(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE}, REQUEST_EXTERNAL_IMAGE_STORAGE_PERMISSION);
            return;
        }
        launchRotateImage();

    }`
if you don't have permissions (first time) the code doesn't call the result callback and doesn't rotate

**Comment by martesabt** [comment]
I got same problem.

In my case I check and manage the permissions with [permission_handler](https://pub.dev/packages/permission_handler).

After accepting all permissions, the `FlutterExifRotation.rotateImage` does nothing the first time you try to pick an image with device camera.

**Comment by juliancesar** [comment]
I got same problem.

**Comment by PocketDaniel** [comment]
I am having the same problem.

Just to double check - I use [permission_handler](https://pub.dev/packages/permission_handler) too and asking for **Permission.storage** (Android: External Storage). After permission was granted `rotateImage()` does not ask for permission, but does not work either for the first time.

Just hypothetically, if I am sure I manage permissions right, is it safe to comment out native permission check (assuming this will fix the problem)? Could there be unwanted consequences?
```
    if (!permissionManager.isPermissionGranted(Manifest.permission.READ_EXTERNAL_STORAGE) || !permissionManager.isPermissionGranted(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
        permissionManager.askForPermission(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE}, REQUEST_EXTERNAL_IMAGE_STORAGE_PERMISSION);
        return;
    }
```

**Comment by infobkm** [comment]
same problem here..
not yet fixed?
any workaround?

**Comment by diver2** [comment]
I use  [permission_handler](https://pub.dev/packages/permission_handler) as @PocketDaniel above. 
I just commented out the code
```java
if (!permissionManager.isPermissionGranted(Manifest.permission.READ_EXTERNAL_STORAGE) || !permissionManager.isPermissionGranted(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
    permissionManager.askForPermission(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE}, REQUEST_EXTERNAL_IMAGE_STORAGE_PERMISSION);
     return;
}
```

and it works. 
HOWEVER, you have to make sure you ask for permissions before.
I'm asking for:
Permission.camera.request() in both platforms (iOS/android)
and 
for iOS: Permission.photos.request();
for android: Permission.storage.request();

and only continue if I have them.
I did not test if you need less than that, maybe only camera already works, or only photos. My use case is getting an image with the camera and rotating.
I'm not applying for a PR cause I think this is not a definitive solution, but it is working now for me
Cheers

**Comment by tstarasinic** [comment]
Is there any progress on this bug ? I also get problem with first use of package.

**Comment by Parthib** [comment]
This fork has a commit that "fixes" the issue if you manage things with permission_handler:

https://github.com/thecasualdev17/flutter_exif_rotation/commit/9c646bb25fef977aecc374b6411bb2f89da42633

In my project I just set my dependency as 

```
  flutter_exif_rotation:
    git:
      url: https://github.com/thecasualdev17/flutter_exif_rotation
```

instead and the bug disappears!

**Comment by NGhebreial** [comment]
I just published a new version with the changes to make it work at the first time
