### ISSUE TITLE
Flutter Web Support

### ISSUE THREAD

**Issue by JamesAllgood** [NGhebreial/flutter_exif_rotation#47]
Will this project ever get flutter web support? 

Would be amazing to use this in my app / be able to export it to the web as well without having to modify lots of code.

**Comment by aytunch** [comment]
@JamesAllgood could you find an alternative for web? Why did you close the issue?

**Comment by NGhebreial** [comment]
I'm not really planning to add support for web tbh, but I will accept PR for this 😄
