### ISSUE TITLE
The plugin doesn't work on ios

### ISSUE THREAD

**Issue by juliengit2** [NGhebreial/flutter_exif_rotation#5]
This plugin works super on android but on ios we get :

> No implementation found for method rotateImage on channel flutter_exif_rotation

pity that it doesn't work on ios...

Any idea when there will be a fix for ios?

**Comment by NGhebreial** [comment]
Yeah, I think is a pity as well, I really would like to implement it for iOS as well but I don't have a Mac and I'm not being able to launch a VM, so far I will not make it, sorry
