### ISSUE TITLE
OutOfMemoryError 

### ISSUE THREAD

**Issue by juliengit2** [NGhebreial/flutter_exif_rotation#6]
When we use this plugin the app crash and we get the following error :

```
Throwing OutOfMemoryError "Failed to allocate a 38340876 byte allocation with 12644112 free bytes and 12MB until OOM"
D/skia    (32656): --- decoder->decode returned false
E/flutter (32656): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.OutOfMemoryError: Failed to allocate a 38340876 byte allocation with 12644112 free bytes and 12MB until OOM
```

**Comment by NGhebreial** [comment]
Hi Julien,
Can you give me more details?
Where is crashing, in the example or in your app?
When is crashing? what action are you doing?
Also I need to know why you think is my plugin, the log trace you put is not enough.

Also I suggest you to take a look to this answer:
https://github.com/facebook/fresco/issues/2128

Thanks :)

**Comment by juliengit2** [comment]
Hi,
I've follow exactly your example and it's crashing when I add this line :

> image = await FlutterExifRotation.rotateImage(path: image.path);

after : 

> File image = await ImagePicker.pickImage(source: ImageSource.gallery);

(as in your example)

(tested with image from camera, images size are about 4-5mo)

I found that if I call FlutterExifRotation.rotateImage  after compressing the image (using FlutterNativeImage.compressImage), then there is no lack of memory and no crash, and the plugin is working well.

**Comment by NGhebreial** [comment]
Hi @juliengit2 
Sorry for the delay.
I've been trying with images with large images and I can't replicate your crash. Is still happening?
