### ISSUE TITLE
I get the following when I select an Image. How to solve it?

### ISSUE THREAD

**Issue by xihuny** [NGhebreial/flutter_exif_rotation#8]
W/ExifInterface( 8452): Skip the tag entry since tag number is not defined: 2
W/ExifInterface( 8452): Stop reading file since a wrong offset may cause an infinite loop: 0
I/chatty  ( 8452): uid=10497(com.xihuny.testapp) Binder:8452_1 identical 2 lines
W/ExifInterface( 8452): Stop reading file since a wrong offset may cause an infinite loop: 0
W/ExifInterface( 8452): Stop reading file since a wrong offset may cause an infinite loop: 0
I/chatty  ( 8452): uid=10497(com.xihuny.testapp) identical 1 line
W/ExifInterface( 8452): Stop reading file since a wrong offset may cause an infinite loop: 0

**Comment by NGhebreial** [comment]
Hi @Xihuny 
I need more information, I never had an issue like this before.
Also I need you to tell me if this is happening also in a real devices because emulators are not 100% reliable

**Comment by ghost** [comment]
Hi @NGhebreial I got the same error when image Source is camera.
