### ISSUE TITLE
Photos added to photo library

### ISSUE THREAD

**Issue by ccadieux** [NGhebreial/flutter_exif_rotation#9]
Currently using this package adds the image to the photo library.
Is it possible to not add the images to the photo library? 

The photos from our app can't go into to the photo library due to it being sensitive info.

**Comment by juliengit2** [comment]
same issue for us

**Comment by NGhebreial** [comment]
The image is added to library because the data is being saved in a file that after is stored directly in the same path.
Maybe I can add a functionality that instead of saving the file just return it
